[package]
name = "mantle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lifx-core = "0.4.0"
get_if_addrs = "0.5.3"
failure = "0.1.8"
eframe = "0.28.1"
egui_extras = { version = "0.28.1", features = ["default", "image"] }
env_logger = { version = "0.11.3", features = ["auto-color", "humantime"] }